<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Pages\Javascript1.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="XmlAccount\AccountResults.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="XmlAccount\AccountResults.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net6.0\XmlQuestions\C-Sharp.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\FrontEnd.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\General.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\Intake.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\Javascript.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\Python.xml" />
    <None Include="bin\Debug\net6.0\XmlQuestions\Scrum.xml" />
  </ItemGroup>

</Project>
